// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package bridge

import (
	"database/sql"

	"github.com/google/uuid"
)

type Profile struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	PictureUrl sql.NullString
}

type UserAccount struct {
	ID    uuid.UUID
	Pwd   string
	Hash  string
	Email string
}
